

name: spug

services:
  spug:
    image: openspug/spug-service
    container_name: spug-app
    tty: true
    restart: on-failure
    environment:
      - SPUG_DOCKER_VERSION=v3.2.7
      - MYSQL_DATABASE=spug
      - MYSQL_USER=spug
      - MYSQL_PASSWORD=spug.cc
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - yycc
  db:
    image: mariadb:10.8.2
    container_name: spug-db
    restart: always
    command: --port 3306 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /data/spug/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=spug
      - MYSQL_USER=spug
      - MYSQL_PASSWORD=spug.cc
      - MYSQL_ROOT_PASSWORD=spug.cc
    networks:
      - yycc
networks:
  yycc:
    driver: bridge