 # author: leon<silenceace@gmail.com>
services:
  metabase:
    image: metabase/metabase:v0.46.6.4
    container_name: app-metabase
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
    environment:
      - MB_DB_FILE=/db/metabase.db
    tty: true
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data/metabase.db:/db/metabase.db
    networks:
      - ycnet
networks:
  ycnet:
    driver: bridge