services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      CPU_CORES: "8"
      DISK_SIZE: "256G"
      DISK2_SIZE: "512G"
      RAM_SIZE: "16G"
      LANGUAGE: "Chinese"
      REGION: "en-US"
      KEYBOARD: "en-US"
      USERNAME: "leo"
      PASSWORD: "ztlakycblek"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - ./share_data:/data
      - ./storage:/storage
      - ./storage2:/storage2
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m