services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      LANGUAGE: "Chinese"
      REGION: "en-US"
      KEYBOARD: "en-US"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - ./share_data:/data
      - ./storage:/storage
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m