version: '3.3'
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: always
    privileged: true
    tty: true
    volumes:
      - ./fb_files:/srv
      - ./filebrowser.db:/database/filebrowser.db
      - ./settings.json:/config/settings.json
    environment:
      - PUID=$$(id -u)
      - PGID=$$(id -g)
    ports:
      - 8080:8080