 # author: leon<silenceace@gmail.com>
 # https://hub.docker.com/r/apache/superset
services:
  superset:
    image: apache/superset
    container_name: app-superset
    mem_limit: 6144m
    user: root
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
    environment:
      SUPERSET_SECRET_KEY: bcb0fd1aad99cf3d6ce1d91a69214762
    ports:
      - 8088:8088
    volumes:
      - ./data/superset_home:/app/superset_home
    networks:
      - ycnet
networks:
  ycnet:
    driver: bridge