version: '3.8'
services:
  app:
    image: dutchcoders/transfer.sh:latest
    privileged: true
    container_name: transfersh
    tty: true
    restart: always
    command: --basedir /tmp --provider local --log /tmp/transfer.log --listener :8080 --random-token-length 7 --purge-days 7 --purge-interval 1 --max-upload-size 10485760
    volumes:
      - ./data/transfersh:/tmp
    ports:
      - 80:8080