 # author: leon<silenceace@gmail.com>
 # https://hub.docker.com/_/mysql?tab=description
version: '3.1'
services:
  mysql:
    image: mysql:5.7.44
    privileged: false
    container_name: db-mysql
    command: 
      # bin log
      --server_id=308
      --max-allowed-packet=67108864
      --log-bin=/var/lib/mysql/mysql-bin
      --sync_binlog=1
      --binlog-ignore-db=mysql
      --binlog_format=ROW
      --log_bin_trust_function_creators=1
      --expire_logs_days=365
      --general-log=1
      --general-log-file=/var/lib/mysql/general-log
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    restart: on-failure
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      CHARACTER_SET_SERVER: utf8mb4
      COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_ROOT_PASSWORD: 7788689
      # Optional
      # MYSQL_DATABASE: blog
      # MYSQL_USER: ublog
      # MYSQL_PASSWORD: 7788689
    volumes:
      # db data、binlog、general log
      - ./db/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  mysql8:
    image: mysql:8.4.3
    privileged: false
    container_name: db-mysql8
    command: 
      --server_id=308
      --max-allowed-packet=67108864
      --log-bin=/var/lib/mysql/mysql-bin
      --sync_binlog=1
      --binlog-ignore-db=mysql
      --binlog_format=ROW
      --log_bin_trust_function_creators=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    restart: on-failure
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      CHARACTER_SET_SERVER: utf8mb4
      COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_ROOT_PASSWORD: 7788689
      # Optional
      # MYSQL_DATABASE: blog
      # MYSQL_USER: ublog
      # MYSQL_PASSWORD: 7788689
    volumes:
      # db data、binlog、general log
      - ./db/mysql8:/var/lib/mysql
    ports:
      - 3307:3306
      