version: '3.8'
services:
  postgres:
    image: postgres:13.11
    restart: unless-stopped
    container_name: app-postgres
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: ksdfjwj3429kjssd
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ycnet
networks:
  ycnet:
    driver: bridge